/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SourceFiles;

/**
 *
 * @author Dilip
 */
public class Score extends javax.swing.JFrame {

    /**
     * Creates new form PlayerOption
     */
    public boolean singlePlay = true;
    PlayerList playerList = new PlayerList();

    public Score() {
        initComponents();
        fillCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        lblWin = new javax.swing.JLabel();
        lblLoss = new javax.swing.JLabel();
        lblDraw = new javax.swing.JLabel();
        cmbList = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblName.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Select Name :");
        getContentPane().add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 184, 250, 40));

        lblWin.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblWin.setForeground(new java.awt.Color(255, 255, 255));
        lblWin.setText("12");
        getContentPane().add(lblWin, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, -1, -1));

        lblLoss.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblLoss.setForeground(new java.awt.Color(255, 255, 255));
        lblLoss.setText("15");
        getContentPane().add(lblLoss, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 352, -1, -1));

        lblDraw.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblDraw.setForeground(new java.awt.Color(255, 255, 255));
        lblDraw.setText("23");
        getContentPane().add(lblDraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 435, 60, 40));

        cmbList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbListActionPerformed(evt);
            }
        });
        getContentPane().add(cmbList, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 185, 200, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Exit.png"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 470, 200, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Win :");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 268, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Loss :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 350, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Draw :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 430, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/BackgroundStart.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbListActionPerformed
        // TODO add your handling code here:
        Human player;
        player = playerList.getPlayers(cmbList.getSelectedItem().toString());
        lblWin.setText(player.getWinCount() + "");
        lblLoss.setText(player.getLossCount() + "");
        lblDraw.setText(player.getDrawCount() + "");

    }//GEN-LAST:event_cmbListActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed
    public void fillCombo() {
        for (int i = 0; i < playerList.getSize(); i++) {
            cmbList.addItem(playerList.getPlayerName(i));
        }
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbList;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblDraw;
    private javax.swing.JLabel lblLoss;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblWin;
    // End of variables declaration//GEN-END:variables
}
