/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view.attendance;

import controller.student.AttendanceController;
import controller.student.StudentDetailController;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.Timer;
import model.student.Attendance;
import model.student.AttendanceSheet;
import model.student.Student;
import utilities.BarcodeReader;
import utilities.ComboBoxUtility;

/**
 *
 * @author Mampitiya
 */
public class AttendanceManagement extends javax.swing.JInternalFrame {
    private Date time;
    private StudentDetailController studentController;
    private AttendanceController attendanceController;
    private BarcodeReader reader;
    private String currentEmployee;
    private AttendanceSheet sheet;
    /**
     * Creates new form Attendance
     */
    public AttendanceManagement() {
        try {
            time = new Date();
            initComponents();
            img2.setPreferredSize(new Dimension(128, 128));
            img2.setMaximumSize(new Dimension(128, 128));
            img2.setMinimumSize(new Dimension(128, 128));
            
            img3.setPreferredSize(new Dimension(128, 128));
            img3.setMaximumSize(new Dimension(128, 128));
            img3.setMinimumSize(new Dimension(128, 128));
            
            imgLbl.setPreferredSize(new Dimension(128, 128));
            imgLbl.setMaximumSize(new Dimension(128, 128));
            imgLbl.setMinimumSize(new Dimension(128, 128));
            
            ComboBoxUtility.setComboItem(idCmbx, "Select studentID from student order by 1");
            ComboBoxUtility.setComboItem(nameCmbx, "Select concat(firstName,' ',lastName) as name from student");
            ComboBoxUtility.setComboItem(classIDList, "Select classID from class order by 1");
            
            JTextField txt1 = (JTextField) idCmbx.getEditor().getEditorComponent();
            new ComboBoxUtility().setSearchableCombo(idCmbx, txt1, "No such student");
            
            JTextField txt2 = (JTextField) nameCmbx.getEditor().getEditorComponent();
            new ComboBoxUtility().setSearchableCombo(nameCmbx, txt2, "No such student");
            
            confirmBtn2.setEnabled(false);
        } catch (SQLException | ClassNotFoundException ex) {
        }
    }

    public AttendanceManagement(StudentDetailController studentController, AttendanceController attendanceController,BarcodeReader reader) {
        try {
            time = new Date();
            initComponents();
            
            ComboBoxUtility.setComboItem(idCmbx1, "Select studentID from student order by 1");
            ComboBoxUtility.setComboItem(nameCmbx1, "Select concat(firstName,' ',lastName) as name from student");
            ComboBoxUtility.setComboItem(classIDList, "Select classID from class order by 1");
            
            JTextField txt1 = (JTextField) idCmbx1.getEditor().getEditorComponent();
            new ComboBoxUtility().setSearchableCombo(idCmbx1, txt1, "No such student");
            
            JTextField txt2 = (JTextField) nameCmbx1.getEditor().getEditorComponent();
            new ComboBoxUtility().setSearchableCombo(nameCmbx1, txt2, "No such student");
            
            confirmBtn2.setEnabled(false);
            sheet = new AttendanceSheet();
        } catch (SQLException | ClassNotFoundException ex) {
        }

        this.studentController = studentController;
        this.attendanceController = attendanceController;
        this.reader = reader;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        timeLabel2 = new javax.swing.JLabel();
        Timer timer = new Timer(1000, new ActionListener(){
            public void actionPerformed(ActionEvent e) { //Timer ticked
                time = new Date();
                String temp[] = time.toString().split(" ");
                timeLabel2.setText(temp[3]);
                repaint();
            }
        }); //Tick every 1000ms, let MyListener listen to the ticks
        timer.start(); //Start the timer

        monthlyFeeStatus = new javax.swing.JLabel();
        dateLabel2 = new javax.swing.JLabel();
        studentIdText2 = new javax.swing.JTextField();
        firstNameText2 = new javax.swing.JTextField();
        lastNameText2 = new javax.swing.JTextField();
        img2 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        confirmBtn2 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        resetBtn2 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        searchBtn2 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        attendanceDetails = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        pictureField = new javax.swing.JLabel();
        classIDList = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        submitSheetBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        timeLabel3 = new javax.swing.JLabel();
        Timer timer1 = new Timer(1000, new ActionListener(){
            public void actionPerformed(ActionEvent e) { //Timer ticked
                time = new Date();
                String temp1[] = time.toString().split(" ");
                timeLabel3.setText(temp1[3]);
                repaint();
            }
        }); //Tick every 1000ms, let MyListener listen to the ticks
        timer1.start(); //Start the timer

        dateLabel3 = new javax.swing.JLabel();
        examFeeLabel = new javax.swing.JLabel();
        studentIdText3 = new javax.swing.JTextField();
        examFeeStatus = new javax.swing.JLabel();
        firstNameText3 = new javax.swing.JTextField();
        lastNameText3 = new javax.swing.JTextField();
        img3 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        confirmBtn3 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        resetBtn3 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        searchBtn3 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        imgLbl = new javax.swing.JLabel();
        snLbl1 = new javax.swing.JLabel();
        nameCmbx1 = new javax.swing.JComboBox();
        siLbl1 = new javax.swing.JLabel();
        idCmbx1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        classCmbBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        confirmBtn = new javax.swing.JButton();
        reasonTxt = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        stuRbtn = new javax.swing.JRadioButton();
        clsRbtn = new javax.swing.JRadioButton();
        studentPane = new javax.swing.JPanel();
        snLbl = new javax.swing.JLabel();
        nameCmbx = new javax.swing.JComboBox();
        siLbl = new javax.swing.JLabel();
        idCmbx = new javax.swing.JComboBox();
        classPane = new javax.swing.JPanel();
        yLbl = new javax.swing.JLabel();
        yearCmbx = new javax.swing.JComboBox();
        cLbl = new javax.swing.JLabel();
        catCmbx = new javax.swing.JComboBox();
        detailLbl = new javax.swing.JLabel();
        reportBtn = new javax.swing.JButton();

        setBorder(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Attendance Management"));

        jLabel19.setText("Monthly Fee :");

        timeLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        timeLabel2.setText("Time: ");

        monthlyFeeStatus.setText("status");

        dateLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dateLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dateLabel2.setText("Date:");

        studentIdText2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                studentIdText2FocusGained(evt);
            }
        });

        jLabel20.setText("Attendance details:");

        confirmBtn2.setText("Confirm");
        confirmBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBtn2ActionPerformed(evt);
            }
        });

        jLabel21.setText("Student ID :");

        resetBtn2.setText("Reset");

        jLabel22.setText("First Name :");

        searchBtn2.setText("Search");

        jLabel23.setText("Last Name :");

        attendanceDetails.setForeground(new java.awt.Color(255, 0, 0));
        attendanceDetails.setText("status");

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Picture"));

        pictureField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pictureField.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/student_images/user.png"))); // NOI18N

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pictureField))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pictureField)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("Class ID :");

        submitSheetBtn.setText("Submit Sheet");
        submitSheetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitSheetBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(505, 505, 505)
                        .addComponent(img2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23)
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addGap(76, 76, 76)
                                        .addComponent(lastNameText2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(timeLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(attendanceDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addGap(22, 22, 22)
                                        .addComponent(monthlyFeeStatus))
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(firstNameText2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel11Layout.createSequentialGroup()
                                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel21)
                                                    .addComponent(jLabel3))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(classIDList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(studentIdText2, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dateLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(submitSheetBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(confirmBtn2)
                                .addGap(44, 44, 44)
                                .addComponent(resetBtn2)
                                .addGap(45, 45, 45)
                                .addComponent(searchBtn2)))
                        .addGap(216, 216, 216)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(timeLabel2)
                    .addComponent(dateLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(classIDList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(studentIdText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(firstNameText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(lastNameText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(monthlyFeeStatus))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(attendanceDetails))))
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(img2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchBtn2)
                            .addComponent(resetBtn2)
                            .addComponent(confirmBtn2)
                            .addComponent(submitSheetBtn))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        String temp[] = time.toString().split(" ");
        dateLabel2.setText(temp[0]+", "+temp[1]+" "+temp[2]+", "+temp[5]);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Weekly Attendance", jPanel3);

        timeLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        timeLabel3.setText("Time: ");

        dateLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dateLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dateLabel3.setText("Date:");

        examFeeLabel.setText("Exam Fee :");

        studentIdText3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                studentIdText3FocusGained(evt);
            }
        });

        examFeeStatus.setText("status");

        jLabel27.setText("Attendance details:");

        confirmBtn3.setText("Confirm");

        jLabel28.setText("Student ID :");

        resetBtn3.setText("Reset");

        jLabel29.setText("First Name :");

        searchBtn3.setText("Search");

        jLabel30.setText("Last Name :");

        jLabel31.setForeground(new java.awt.Color(255, 0, 0));
        jLabel31.setText("status");

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder("Picture"));

        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/student_images/user.png"))); // NOI18N

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(505, 505, 505)
                        .addComponent(img3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel13Layout.createSequentialGroup()
                                        .addComponent(jLabel28)
                                        .addGap(18, 18, 18)
                                        .addComponent(studentIdText3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel29)
                                    .addGroup(jPanel13Layout.createSequentialGroup()
                                        .addGap(77, 77, 77)
                                        .addComponent(firstNameText3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel30)
                                    .addGroup(jPanel13Layout.createSequentialGroup()
                                        .addGap(76, 76, 76)
                                        .addComponent(lastNameText3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(timeLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel13Layout.createSequentialGroup()
                                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel13Layout.createSequentialGroup()
                                        .addComponent(examFeeLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(examFeeStatus)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dateLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(confirmBtn3)
                                .addGap(44, 44, 44)
                                .addComponent(resetBtn3)
                                .addGap(45, 45, 45)
                                .addComponent(searchBtn3)))
                        .addGap(206, 206, 206)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(timeLabel3)
                    .addComponent(dateLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(studentIdText3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(firstNameText3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(lastNameText3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(examFeeLabel)
                            .addComponent(examFeeStatus))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(jLabel31))))
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(img3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchBtn3)
                            .addComponent(resetBtn3)
                            .addComponent(confirmBtn3))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        String temp2[] = time.toString().split(" ");
        dateLabel3.setText(temp2[0]+", "+temp2[1]+" "+temp2[2]+", "+temp2[5]);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(" Exam Attendance", jPanel2);

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder("Image"));

        imgLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/student_images/user.png"))); // NOI18N

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imgLbl))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgLbl)
        );

        snLbl1.setText("Student Name: ");

        nameCmbx1.setEditable(true);
        nameCmbx1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameCmbx1ActionPerformed(evt);
            }
        });

        siLbl1.setText("Student ID: ");

        idCmbx1.setEditable(true);
        idCmbx1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idCmbx1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Class : ");

        classCmbBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));

        jLabel2.setText("Reason: ");

        confirmBtn.setText("Confirm");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(confirmBtn)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(snLbl1)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(classCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(nameCmbx1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(siLbl1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(idCmbx1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(reasonTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(snLbl1)
                    .addComponent(nameCmbx1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idCmbx1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(siLbl1))
                .addGap(18, 18, 18)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(classCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(reasonTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Early Leaving", jPanel4);

        jPanel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        buttonGroup1.add(stuRbtn);
        stuRbtn.setSelected(true);
        stuRbtn.setText("Individual Student Report");
        stuRbtn.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                stuRbtnItemStateChanged(evt);
            }
        });

        buttonGroup1.add(clsRbtn);
        clsRbtn.setText("Overall Class Report");
        clsRbtn.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                clsRbtnItemStateChanged(evt);
            }
        });

        studentPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        snLbl.setText("Student Name: ");

        nameCmbx.setEditable(true);
        nameCmbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameCmbxActionPerformed(evt);
            }
        });

        siLbl.setText("Student ID: ");

        idCmbx.setEditable(true);
        idCmbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idCmbxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout studentPaneLayout = new javax.swing.GroupLayout(studentPane);
        studentPane.setLayout(studentPaneLayout);
        studentPaneLayout.setHorizontalGroup(
            studentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(snLbl)
                .addGap(10, 10, 10)
                .addComponent(nameCmbx, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(siLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(idCmbx, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        studentPaneLayout.setVerticalGroup(
            studentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(studentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(snLbl)
                    .addComponent(nameCmbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idCmbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(siLbl))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        classPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        yLbl.setText("Year: ");
        yLbl.setEnabled(false);

        yearCmbx.setEditable(true);
        yearCmbx.setEnabled(false);
        yearCmbx.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                yearCmbxItemStateChanged(evt);
            }
        });

        cLbl.setText("Category: ");
        cLbl.setEnabled(false);

        catCmbx.setEditable(true);
        catCmbx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Mass", "Revision" }));
        catCmbx.setEnabled(false);
        catCmbx.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                catCmbxItemStateChanged(evt);
            }
        });

        detailLbl.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout classPaneLayout = new javax.swing.GroupLayout(classPane);
        classPane.setLayout(classPaneLayout);
        classPaneLayout.setHorizontalGroup(
            classPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(classPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(classPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(classPaneLayout.createSequentialGroup()
                        .addComponent(yLbl)
                        .addGap(57, 57, 57)
                        .addComponent(yearCmbx, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cLbl)
                        .addGap(18, 18, 18)
                        .addComponent(catCmbx, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, classPaneLayout.createSequentialGroup()
                        .addComponent(detailLbl)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        classPaneLayout.setVerticalGroup(
            classPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(classPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(classPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yLbl)
                    .addComponent(yearCmbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cLbl)
                    .addComponent(catCmbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(detailLbl)
                .addContainerGap())
        );

        reportBtn.setText("Generate Report");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(classPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(reportBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(stuRbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clsRbtn)
                    .addComponent(studentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stuRbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(studentPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(clsRbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(classPane, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(reportBtn)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reports", jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void setCurrentEmployee(String username) {
        this.currentEmployee = username;
    }
    private void nameCmbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameCmbxActionPerformed

    }//GEN-LAST:event_nameCmbxActionPerformed

    private void idCmbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idCmbxActionPerformed

    }//GEN-LAST:event_idCmbxActionPerformed

    private void yearCmbxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_yearCmbxItemStateChanged
        if (catCmbx.getSelectedItem().toString().isEmpty()) {
            detailLbl.setText("Select a category");
        }
    }//GEN-LAST:event_yearCmbxItemStateChanged

    private void catCmbxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_catCmbxItemStateChanged
        if (yearCmbx.getSelectedItem().toString().isEmpty()) {
            detailLbl.setText("Select a category");
        }
    }//GEN-LAST:event_catCmbxItemStateChanged

    private void stuRbtnItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_stuRbtnItemStateChanged
        if(stuRbtn.isSelected()){
            Component clsComp[] = classPane.getComponents();
            Component stdComp[] = studentPane.getComponents();
            for (Component component : clsComp) {
                component.setEnabled(false);
            }
            
            for (Component component : stdComp) {
                component.setEnabled(true);
            }
        }
    }//GEN-LAST:event_stuRbtnItemStateChanged

    private void clsRbtnItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_clsRbtnItemStateChanged
        if(clsRbtn.isSelected()){
            Component clsComp[] = classPane.getComponents();
            Component stdComp[] = studentPane.getComponents();
            for (Component component : clsComp) {
                component.setEnabled(true);
            }
            
            for (Component component : stdComp) {
                component.setEnabled(false);
            }
        }
    }//GEN-LAST:event_clsRbtnItemStateChanged

    private void nameCmbx1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameCmbx1ActionPerformed
        String name = "";
        if (nameCmbx1.getSelectedItem() != null && nameCmbx1.getSelectedIndex() != 0) {
            name = nameCmbx1.getSelectedItem().toString();
            Student student = studentController.searchStudentByName(name);
            idCmbx1.setSelectedItem(student.getStudentID());
        }
    }//GEN-LAST:event_nameCmbx1ActionPerformed

    private void idCmbx1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idCmbx1ActionPerformed
        String id = "";
        if (idCmbx1.getSelectedItem() != null && idCmbx1.getSelectedIndex() != 0) {
            try {
                id = idCmbx1.getSelectedItem().toString();
                Student student = studentController.searchStudentByID(id);
                nameCmbx1.setSelectedItem(student.getFirstName()+" "+student.getLastName());
                ComboBoxUtility.setComboItem(classCmbBox, "SELECT classID FROM classdetail WHERE studentID='"+id+"'");
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(AttendanceManagement.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_idCmbx1ActionPerformed

    private void studentIdText2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_studentIdText2FocusGained
        String id = reader.getNextBarcode();
        studentIdText2.setText(id);

        if (id != null) {
            Student student = studentController.searchStudentByID(id);
            firstNameText2.setText(student.getFirstName());
            lastNameText2.setText(student.getLastName());
            confirmBtn2.setEnabled(true);
        }
    }//GEN-LAST:event_studentIdText2FocusGained

    private void studentIdText3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_studentIdText3FocusGained
        String id = reader.getNextBarcode();
        studentIdText3.setText(id);

        if (id != null) {
            Student student = studentController.searchStudentByID(id);
            firstNameText3.setText(student.getFirstName());
            lastNameText3.setText(student.getLastName());
        }
    }//GEN-LAST:event_studentIdText3FocusGained

    private void confirmBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBtn2ActionPerformed
        String classID = classIDList.getSelectedItem().toString();
        String studentID = studentIdText2.getText();
        
        Attendance record = new Attendance(studentID,System.currentTimeMillis(),currentEmployee);
        System.out.println(currentEmployee);
        record.setClassID(classID);
        
        sheet.addRecord(record);
        clearFields();   
    }//GEN-LAST:event_confirmBtn2ActionPerformed

    private void submitSheetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitSheetBtnActionPerformed
        boolean res = attendanceController.addAttendanceSheet(sheet);
        
        if (res) {
            JOptionPane.showMessageDialog(this, "Successfully Added!");
        }else{
            JOptionPane.showMessageDialog(this, "Failed to add! Check entered information again.");
        }    
    }//GEN-LAST:event_submitSheetBtnActionPerformed

    private void clearFields(){
        studentIdText2.setText("");
        firstNameText2.setText("");
        lastNameText2.setText("");
        monthlyFeeStatus.setText("");
        attendanceDetails.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel attendanceDetails;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel cLbl;
    private javax.swing.JComboBox catCmbx;
    private javax.swing.JComboBox classCmbBox;
    private javax.swing.JComboBox classIDList;
    private javax.swing.JPanel classPane;
    private javax.swing.JRadioButton clsRbtn;
    private javax.swing.JButton confirmBtn;
    private javax.swing.JButton confirmBtn2;
    private javax.swing.JButton confirmBtn3;
    private javax.swing.JLabel dateLabel2;
    private javax.swing.JLabel dateLabel3;
    private javax.swing.JLabel detailLbl;
    private javax.swing.JLabel examFeeLabel;
    private javax.swing.JLabel examFeeStatus;
    private javax.swing.JTextField firstNameText2;
    private javax.swing.JTextField firstNameText3;
    private javax.swing.JComboBox idCmbx;
    private javax.swing.JComboBox idCmbx1;
    private javax.swing.JLabel img2;
    private javax.swing.JLabel img3;
    private javax.swing.JLabel imgLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField lastNameText2;
    private javax.swing.JTextField lastNameText3;
    private javax.swing.JLabel monthlyFeeStatus;
    private javax.swing.JComboBox nameCmbx;
    private javax.swing.JComboBox nameCmbx1;
    private javax.swing.JLabel pictureField;
    private javax.swing.JTextField reasonTxt;
    private javax.swing.JButton reportBtn;
    private javax.swing.JButton resetBtn2;
    private javax.swing.JButton resetBtn3;
    private javax.swing.JButton searchBtn2;
    private javax.swing.JButton searchBtn3;
    private javax.swing.JLabel siLbl;
    private javax.swing.JLabel siLbl1;
    private javax.swing.JLabel snLbl;
    private javax.swing.JLabel snLbl1;
    private javax.swing.JRadioButton stuRbtn;
    private javax.swing.JTextField studentIdText2;
    private javax.swing.JTextField studentIdText3;
    private javax.swing.JPanel studentPane;
    private javax.swing.JButton submitSheetBtn;
    private javax.swing.JLabel timeLabel2;
    private javax.swing.JLabel timeLabel3;
    private javax.swing.JLabel yLbl;
    private javax.swing.JComboBox yearCmbx;
    // End of variables declaration//GEN-END:variables
}
